name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2
      
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ThayzaMaciel
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Set up Git
      - name: Set up Git
        run: |
          git config --local user.email "macielthayzale@gmail.com"
          git config --local user.name "Thayza"

      # Push to output branch
      - name: Push to output branch
        run: |
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Update snake animation"
          git push origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
